app = 'snd-reverse-1625'
primary_region = 'sin'

[http_service]
  internal_port = 8053
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
